import React from 'react';
import Typography from '@material-ui/core/Typography';

function AboutUs() {
	return (
		<div>
			sfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslafsfdafkjsdhafksadghfudjkslaf
		</div>
	);
}

export default AboutUs;
